### ISSUE TITLE
Something wrong with add_pages 

### ISSUE THREAD

**Issue by Merino** [mreiferson/py-wkhtmltox#1]
Hey Matt, 

I've got a little problem with py-wkhtmltox. When i run this test script i aspect two files. The first file renders as aspected. Only the second file renders the first pages and then adds the second pages. Somehow the pages var is remember!!  

import wkhtmltox

pdf = wkhtmltox.Pdf()
pdf.set_global_setting('out', 'one.pdf')
pdf.add_page({'page': 'http://www.visionaryrenesis.com'})
pdf.add_page({'page': 'http://www.google.com'})
pdf.convert()

doc = wkhtmltox.Pdf()
doc.set_global_setting('out', 'two.pdf')
doc.add_page({'page': 'http://www.tweakers.net'})
doc.convert()

**Comment by mreiferson** [comment]
this should be fixed, please pull, recompile, and let me know...

**Comment by Merino** [comment]
Sorry, 

I had no time to check it sooner, but it works perfectly. 

Thanks
