### ISSUE TITLE
Install on MacOS 10.5.8

### ISSUE THREAD

**Issue by django-rdf-tools** [mreiferson/py-wkhtmltox#2]
I've installed wkhtmltopdf and wkhtmltoimage binaries,
along with the two requirements , DL and include folder
the install script worked, but as soon as I try to `import wkhtmltox` , I get :
    ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wkhtmltox.so, 2): Symbol not found: _wkhtmltoimage_convert
    Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wkhtmltox.so
    Expected in: dynamic lookup

What `Symbol not found: _wkhtmltoimage_convert` means here ?
Thanks for your work

**Comment by mreiferson** [comment]
Can you paste the output of the setup.py install?

**Comment by django-rdf-tools** [comment]
Sure, here it is:
I used `libwkhtmltox-OSX-0.10.0_rc2.tar.bz2`

running install
running build
running build_ext
building 'wkhtmltox' extension
creating build
creating build/temp.macosx-10.5-fat3-2.7
gcc-4.0 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch ppc -arch x86_64 -g -O2 -DNDEBUG -g -O3 -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c wkhtmltox.c -o build/temp.macosx-10.5-fat3-2.7/wkhtmltox.o
creating build/lib.macosx-10.5-fat3-2.7
gcc-4.0 -arch i386 -arch ppc -arch x86_64 -isysroot / -g -bundle -undefined dynamic_lookup build/temp.macosx-10.5-fat3-2.7/wkhtmltox.o -lwkhtmltox -o build/lib.macosx-10.5-fat3-2.7/wkhtmltox.so
ld warning: in /usr/local/lib/libwkhtmltox.dylib, file is not of required architecture
ld warning: in /usr/local/lib/libwkhtmltox.dylib, file is not of required architecture
running install_lib
copying build/lib.macosx-10.5-fat3-2.7/wkhtmltox.so -> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
running install_egg_info
Writing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_wkhtmltox-0.2-py2.7.egg-info

**Comment by mreiferson** [comment]
These lines:

ld warning: in /usr/local/lib/libwkhtmltox.dylib, file is not of required architecture
ld warning: in /usr/local/lib/libwkhtmltox.dylib, file is not of required architecture

That download you used for libwkhtmltox is i386 (32bit).  It looks like you've installed Python 2.7 on your Mac (presumably 64-bit).

It's trying to load the 64-bit version of libwkhtmltox but can't find it.  If you don't want to build the 64-bit version of libwkhtmltox yourself (which takes a bit of time to configure/compile) you can run a 32-bit version of Python on your mac.

**Comment by django-rdf-tools** [comment]
that was the problem, thanks !
My new problem is to find how to fix my virtualenvs that do not work anymore since the downgrade to 32-bit...
