### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by mbrochh** [mreiferson/py-wkhtmltox#3]
I'm a bit lost trying to install this on my Ubuntu machine.
- I cloned this repo
- I cloned https://github.com/antialize/wkhtmltopdf
- I copied kwhtmltopdf/include/\* to /usr/local/include/
- I downloaded http://wkhtmltopdf.googlecode.com/files/libwkhtmltox-0.11.0_rc1-i386.tar.bz2 and copied it to /usr/local/lib/

I think now I should meet the prerequisites?

When I try python setup.py install in my venv I get the following:

python setup.py install
running install
running build
running build_ext
building 'wkhtmltox' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c wkhtmltox.c -o build/temp.linux-i686-2.7/wkhtmltox.o
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions build/temp.linux-i686-2.7/wkhtmltox.o -lwkhtmltox -o build/lib.linux-i686-2.7/wkhtmltox.so
/usr/bin/ld: cannot find -lwkhtmltox
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by mreiferson** [comment]
is your ubuntu machine 64-bit?  if so, only 32-bit pre-built binaries are provided from the `wkhtmltopdf` repo... you'll have to build your own 64-bit binary of `libwkhtmltox`

**Comment by mbrochh** [comment]
No it is a 32 bit installation.

**Comment by viniciuscainelli** [comment]
Hey, unpack .tar.bz2 file

tar -jvxf libwkhtmltox-0.11.0_rc1-i386.tar.bz2 

And copy libwkhtmltox-0.11.0_rc1-i386/lib/libwkhtmltox.so  -> /usr/local/lib/libwkhtmltox.so

=]

**Comment by viniciuscainelli** [comment]
And, i have an error:

ImportError: libwkhtmltox.so.0: cannot open shared object file: No such file or directory

When I call: python test_image.py

I resolved with:

export LD_LIBRARY_PATH=/usr/local/lib

=]

**Comment by fre-sch** [comment]
Regarding the ImportError, this fixes it for me (on Ubuntu 12.04):
- `sudo ln -s /usr/local/lib/libwkhtmltox.so /usr/local/lib/libwkhtmltox.so.0`
- `sudo ldconfig`
