### ISSUE TITLE
cannot find -lwkhtmltox

### ISSUE THREAD

**Issue by amrnegm** [mreiferson/py-wkhtmltox#6]
I am using the python binding on my local machine so fine(ubuntu 11.10). when I try to install the binding on a shared host it can't install. Of course I don't have write access on the /usr directory to copy dependencies as in the readme file. 

So I made a $HOME/include/ dir and copied the wkhtmltopdf/include/wkhtmltox dir to it. then added the dir path to C_INCLUDE_PATH. I wrote the following lines in the .bashrc file:

```
 C_INCLUDE_PATH=~/include/
 export C_INCLUDE_PATH
```

and copied the wkhtmltox.c and wkhtmltox.pyx files to ~/lib/, and added the following lines to .bashrc file:

```
 LD_LIBRARY_PATH=~/lib/
 export LD_LIBRARY_PATH
```

when I run python2.7 setup.py install, the following error rises 

```
 /usr/bin/ld: cannot find -lwkhtmltox
```

**Comment by mreiferson** [comment]
@amrnegm you need the actual wkhtmltox **library** files in your `lib` directory, not the extensions source and Cython files...

**Comment by amrnegm** [comment]
i actually gave up the library, but thanks for response
